### ISSUE TITLE
Borders issues

### ISSUE THREAD

**Issue by Ancymonek** [openstreetmap-polska/openaedmap-frontend#104]
As I pointed out on Discord:
- Somaliland issue:
![obraz](https://user-images.githubusercontent.com/16021640/208771384-a80e069b-2384-4fd9-8077-5ad139ca34de.png)
https://dev.openaedmap.org/#map=5/9.32/44.67

- Northern and Southern borders are also not perfect:
![obraz](https://user-images.githubusercontent.com/16021640/208771689-0947d52b-2d8e-400c-8b16-4e9059320102.png)
https://dev.openaedmap.org/#map=5/82.65/-25.31

- other regions look weird also: 
![obraz](https://user-images.githubusercontent.com/16021640/208771887-13ec9cbc-da63-4d5d-8edd-23ebb4261dc7.png)
https://dev.openaedmap.org/#map=5/45.63/49.39

**Comment by ttomasz** [comment]
Correct me if I'm wrong but Somaliland doesn't have ISO code since it's unrecognized internationally. If that's the case it won't be added. I'm using Natural Earth's dataset for country borders that's based on sovereignty. If another of their datasets is more apt please let me know which one, one that I tested seemed too complicated to use since it had overlapping borders and I wasn't able to quickly ascertain how to get the borders out of the file :sweat_smile:

**Comment by ttomasz** [comment]
Borders are simplified before rendering using Postgis function `ST_SimplifyPreserveTopology(ST_Transform(ST_Intersection(geometry, ST_MakeEnvelope(-180, -85, 180, 85, 4326)), 3857), 5000)`. I'm open to other approaches if anyone has better value (than 5000) or different approach altogether.

**Comment by Zaczero** [comment]
The borders are fetched from https://github.com/nvkelso/natural-earth-vector. This has always been this way, and there are arguments against switching to OSM-borders like vandalism or poor data. Maybe we could use https://daylightmap.org/admin-boundaries.html one day, but the current solution works just fine. In the new release of the backend, an auto-update feature has been added where it updates boundaries once a day, this should resolve most of the issues.
