### ISSUE TITLE
Display photos of AED

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#128]
First we should handle [`image` tag](https://wiki.openstreetmap.org/wiki/Key:image). 
We can consider support for [`wikimedia_commons` tag](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons).
There should be list of thumbnails which can be clicked to show full image.
Thumbnails would need to be generated on backend.

**Comment by Zaczero** [comment]
Why, precisely, is it marked as "awaiting-upstream"? The node information already provides complete data (including tags in mention). There doesn't seem to be any additional heavy processing required from the backend.

**Comment by ttomasz** [comment]
The original idea was that openaedmap would able to display (and add) photos of AEDs.
Backend was supposed to be able to handle image uploads as well as return list of urls of photos for a given node (plus possible features related to moderation like reporting photos to be deleted).
Hence `awaiting-upstream` label.

No one implemented it in the backend however and the other idea surfaced to use image tags and wikimedia commons.
This is described by the comment.

Reasons for the original idea of backend handling images:
- OSM tags are bad at handling anything other than simple string -> string key-value mappings so working on collections associated with a given object/tag simply sucks. It's usually handled either via storing values in a single tag separated by e.g. `;` or by creating tags with appended numbers e.g. `image_1`, `image_2`, etc. First one works for very simple values like numbers/ids in `ref`. Second in my personal opinion is very tiresome to parse and would result in a lot of useless object versions.
- Using other sites for hosting like wikimedia commons would make for bad user experience for uploading images. Users would need to create a separate account for photo uploads to authenticate to wikimedia. Using some bot account is a risk of getting banned and losing the functionality altogether if someone at wikimedia does not like our uploads (similar reason why we ask users to use their own OSM accounts instead of having a single bot account and no login on the page)

**Comment by starsep** [comment]
I implemented parsing `image`/`wikimedia_commons` tags in https://github.com/openstreetmap-polska/openaedmap-backend/commit/4dbe965006abe998854bcae5e8b83e7744963ebf
It can be used as a base for implementation in the new backend.
I am not claiming it's perfect by any means. Likely it doesn't handle all possible cases and hasn't been used in production yet.

Unfortunately I won't be able to work on that in the near future
