### ISSUE TITLE
Because the OSM data contains translations from different regions, the list is too wide.

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap-polska/openaedmap-frontend#173]
For example, [Bosna i Hercegovina / Босна и Херцеговина](https://www.openstreetmap.org/relation/2528142), was translated to similar but different name in different Chinese using region, but looks like data extract use "name:zh", so it have to widden as the longest string.

<img src="https://github.com/openstreetmap-polska/openaedmap-frontend/assets/42690037/a6f10051-a84c-4841-83ad-274110bb5326" width=350px />

Thus current openAEDmap using ["zh-Hans"](https://github.com/openstreetmap-polska/openaedmap-frontend/blob/dev/public/locales/zh-Hans/translation.json) and ["zh-Hant"](https://github.com/openstreetmap-polska/openaedmap-frontend/blob/dev/public/locales/zh-Hant/translation.json), those 2 different locales, why not use corresponding ["name:zh-Hans"](https://taginfo.openstreetmap.org/keys/name%3Azh-Hans#overview) and ["name:zh-Hant"](https://taginfo.openstreetmap.org/keys/name%3Azh-Hant#overview) while extract data?

Similar situations can also be seen [Tuvalu](https://www.openstreetmap.org/relation/2177266)

---

If maintainers thinks that there is little benefit from fixing the issue, you are welcome to close the issue directly, no problem

**Comment by Zaczero** [comment]
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/89bbebfd-c689-4ec6-aeed-2a0772414b96)

Backend already returns regional translations. Seems like an issue in the frontend.

**Comment by Zaczero** [comment]
@ttomasz

**Comment by ttomasz** [comment]
> @ttomasz

Sorry I won't have time in the nearest future

**Comment by starsep** [comment]
I created fix for it: https://github.com/openstreetmap-polska/openaedmap-frontend/commit/7eba7a3a3d2ae13230d66ff3e72f770ef4072064
Current logic:
1. Use full language with variant if returned from backend (example: `ZH-HANT`)
2. Use basic language code if returned from backend (example `ZH`)
3. Use default name of country as fallback


For Tuvalu with `ZH-HANT` there is issue because only variants of the language are returned:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/21780db7-d5e9-4334-9fff-bc41132aed83)

**Comment by LaoshuBaby** [comment]
> For Tuvalu with `ZH-HANT` there is issue because only variants of the language are returned:

Yes, this is a very bad problem, because when HK and TW are translated with different names but both are in Traditional Chinese, the communities in these two places have not been able to summarize the rules.

Since there is a fallback mechanism, it seems that the problem should be solved.
