### ISSUE TITLE
Remove Cloudflare beacon

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#206]
I suggest we remove the Cloudflare beacon. We already have sufficient analytics from the request count. If we really need to measure the performance of something, we should prefer using our in-house Sentry instance. Thoughts?

https://github.com/openstreetmap-polska/openaedmap-frontend/blob/8882569210f06861741874bc4b0d22e095ad8a7b/index.html#L21

**Comment by ttomasz** [comment]
Where do we store info like this now? (Not all of that is needed but views, visitors, referrers, browsers is useful)
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/31594210/bd6e3479-12c8-4a12-b47e-6391aeced0e2)
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/31594210/7faa480c-2df3-480a-ac9e-5fc4e185ccfd)

**Comment by Zaczero** [comment]
I believe the analysis you have mentioned, will work without the JavaScript snippet. This information is contained within HTTP requests headers. The following is not possible without running JS but I it's unnecessary for us:

![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/b0fefedf-fc4b-49eb-b74d-3cc51f28d69c)

**Comment by ttomasz** [comment]
> I believe the analysis you have mentioned, will work without the JavaScript snippet. This information is contained within HTTP requests headers. (...)

Yes but not for free, it requires some kind of analysis/parsing/work/etc (basically time).

I tried that already in 2022 with the old aed site because people were suggesting the same thing about removing cloudflare analytics: https://discord.com/channels/783754873861963786/918900705182511145/959184284852293712
it used https://goaccess.io/ and with that we could host a public dashboard with basic info: https://aed.openstreetmap.org.pl/stats/report.html

It just required a little scripting to figure out a a good nginx configuration and a cron script that could append data from new logfiles.
There was literally zero interest from the community in helping so I abandoned it and kept with cloudflare analytics that required zero work and worked flawlessly all this time.

**Comment by Zaczero** [comment]
What I meant is that Cloudflare should be able to provide such basic information without the beacon, no? Just the analytics dashboard will be less detailed or maybe I'm wrong about this. It's definitely worth trying out for a day or two and see.

**Comment by Zaczero** [comment]
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/40b426fa-d31e-4e61-9c12-9686c95e6e70)

We already proxy all of our traffic through Cloudflare so they should be able to collect this information even without the beacon.

**Comment by ttomasz** [comment]
Ah you meant that beacon is redundant since we are using Cloudflare CDN now. Then yes you're correct we can remove the beacon.
