### ISSUE TITLE
Defibrillator with no access tag do not appear on mobile

### ISSUE THREAD

**Issue by LySioS** [openstreetmap-polska/openaedmap-frontend#81]
This is the same bug than https://github.com/openstreetmap-polska/openaedmap-frontend/issues/74.

It was closed, but the bug still remains when accessing openaedmap on a mobile phone

**Comment by LySioS** [comment]
defib with access=no are grey on mobile instead of red. Maybe it's the cause of the bug

**Comment by Ancymonek** [comment]
> defib with access=no are grey on mobile instead of red. Maybe it's the cause of the bug

Hey, please verify. It should be fixed with commit https://github.com/openstreetmap-polska/openaedmap-frontend/commit/fa836807b56e68d2542fc0a8a6eb37a6ca5312dd

For me it works well (icons are red) on mobile:
![obraz](https://user-images.githubusercontent.com/16021640/204651235-32479a36-263c-49cd-9718-85ac635fff7f.png)

**Comment by LySioS** [comment]
Indeed, it works on the dev platform. Thank you for your work !
